### ISSUE TITLE
demo install

### ISSUE THREAD

**Issue by JoinTees** [gggeek/phpxmlrpc#108]
Hello, I can't control the server and I can't download the demo examle.
composer says: Failed to download phpxmlrpc/phpxmlrpc from source: git was not found in your PATH, skipping source download
    Now trying to download from dist
Is there another way to download the setup templates?
Thank you for the advice.

**Comment by gggeek** [comment]
Hello.

If I understand correctly your situation, you'd like to download the demo code, but it is impossible to do so on the server where you are installing the library, because it misses `git`, and this makes Composer unable to install the library from source, and when Composer installs from tarballs, the demo files are not included.

This is indeed a situation that I did not foresee.

The quickest workarounds that I can think of are:

1. check out (ie. look at) the demo files online on github. If you find anything useful in them, copy-paste it locally
2. get the demo files locally on another server (or virtual machine) which has git available. You can then either just clone this repository, or use `composer install --prefer-install=source`

If this is something difficult for you to do, I will try to find a better solution - maybe by making the demo files available as a separate package directly from the GitHub Release page.

I am a bit loath to bring back the demo code to the default set of files which gets installed via every composer installation because 1. I like lean and mean composer dependencies, which reduce download time and disk space used, and 2. I'd rather avoid the case where some user leaves the vendor folder accessible from the internet, and some miscreant finds a way to abuse access to the demo files - which for this library are by design able to do stuff when accessed directly over http...

**Comment by gggeek** [comment]
PS: in case this was not clear from the beginning: as their name implies, the demo files are just that - code examples, which are in no way necessary for a working application to use the phpxmlrpc library.

One more tip which I can give is to take a look at the examples in the user manual, which I have been working hard on refreshing in the last few days. It can be seen online at https://github.com/gggeek/phpxmlrpc/blob/master/doc/manual/phpxmlrpc_manual.adoc

**Comment by JoinTees** [comment]
Thank you for your response.
Be sure not to include the demo in the production code.
It used to be a problem for me to clear the test codes too.

I'm testing minimal code, and I've looked in the description, but I just don't see it. I keep getting "Code: 17 Reason: 'Internal server error: no function matches method'" coming back.
I hope a working demo would rub my eyes.
`function getData($req){
			 $sno = $req->getParam(0);
			 $snv = $sno->scalarval();
			 if($snv=='12345') $s='OK, Hello';
			 else $s='bye,bye '.$snv;
			return new PhpXmlRpc\Response(new Value($s));
		}
		$this->methods = array(
				"getData" => array(
						"function" => "getData",
						"signature" =>array(array(Value::$xmlrpcString, Value::$xmlrpcString)),
						"docstring" => "Test server back)."
				),
		);
		//create server
		$this->server = new PhpXmlRpc\Server($this->methods, false);
		$this->server->setDebug(3);
		$this->server->exception_handling = "UTF-8";
		$this->server->service();`

**Comment by gggeek** [comment]
At a very first glance your code seems right. Are you sure that the `getData` function is available in the global scope?

**Comment by gggeek** [comment]
ps: I tested the following code (taken from yours and slightly reformatted) and it does work:

```php
<?php

require_once __DIR__ . '/src/Autoloader.php';
PhpXmlRpc\Autoloader::register();
use PhpXmlRpc\Value;

function getData($req) {
    $sno = $req->getParam(0);
    $snv = $sno->scalarval();
    if ($snv == '12345')
        $s = 'OK, Hello';
    else
        $s = 'bye,bye ' . $snv;
    return new PhpXmlRpc\Response(new Value($s));
}

$methods = array(
    "getData" => array(
        "function" => "getData",
        "signature" => array(
            array(Value::$xmlrpcString, Value::$xmlrpcString)
        ),
        "docstring" => "Test server back."
    ),
);

// create server
$server = new PhpXmlRpc\Server($methods, false);
$server->setDebug(3);
//$server->exception_handling = "UTF-8";
$server->service();
```

Which confirms my suspicion that in your case there must be some scoping issue at play. Maybe you could replace `getData` with an object's method?

**Comment by gggeek** [comment]
> I was able to download the demo using TortoiseSVN. :)

I hope you mean `TortoiseGit` ? :-D

If the function you want to register is a method of the current object, it should work by using `"function" => array($this, 'methodName')` in the dispatch map

**Comment by JoinTees** [comment]
It's already working.
Thanks for support. I wouldn't have given it without your information.
Inspiration for the manual :)
p.s. really good old Tortoise https://tortoisesvn.net/ pulled the whole repository from github.

**Comment by gggeek** [comment]
> Inspiration for the manual :)

I'll add this to my todo-list for sure

**Comment by gggeek** [comment]
FYI: I added a note to TortoiseSVN as a way to get the demo files in the manual.
I also made the actual demo files available as a separate package which can just be downloaded from github, starting with release https://github.com/gggeek/phpxmlrpc/releases/tag/4.9.4
