### ISSUE TITLE
Resolved

### ISSUE THREAD

**Issue by yugenekr** [gggeek/phpxmlrpc#36]

**Comment by gggeek** [comment]
Hello.
I surmise you found a solution to your problem since you have closed the ticket.

Just one word of warning: even outside of xml-rpc, you should never use floating point numbers for economic transactions. There are round-off errors involved with floating point numbers. The easy solution is to multiply all amounts by 100 (since you round to 2 decimals anyway) and use integers.

Bye
Gaetano
