### ISSUE TITLE
 XML error: No memory

### ISSUE THREAD

**Issue by gabrielspiteri-highlight** [gggeek/phpxmlrpc#70]
Hi 

I am getting the following error when attempting to parse a pretty large piece of XML. 

 XML error: No memory

From research I did it seems that in libxml 2.7.x a hard coded limit of 10MB was introduced. Thus when the Request class calls xml_parse on line 291 the no memory error is triggered. 

I have managed to solve the issue by putting the xml into a temp file then reading it in chunks in a while loop and feeding it slowly to the xml_parse function with the is_final parameter being true or false depending on if the end of file is reached. 

Should I attempt to push you a pull request for this?

Thanks

**Comment by gggeek** [comment]
Hello.
Thanks for letting me know.

I did a minimum of googling around today, and from what I understood, the code of phpxmlrpc does currently use php's 'xml parser' extension, which is somehow built on top of an 'expat compatibility layer' and powered by libxml under the hood (see: https://www.php.net/manual/en/xml.requirements.php).  

Apparently it is possible to make usage of the "real expat" for powering the 'xml parser' extension, but I never tried that out, and it is not clear from the php manual if in order to achieve that a recompile is necessary, or just playing around with static libraries and LD_PRELOAD...
On the other hand, some sites that benchmark the xml parsers seem to indicate that, as long as there is no building of the dom tree involved, libxml is as fast as expat, or faster.
These two aspects make me think that the way forward is to stick with libxml and eschew usage of expat.

The question then becomes: how to allow parsing for big xml files?
I see two options:
a) keep using the current xml parsing code and allow stream-based reading, as you did
b) rewrite the xml parsing code on top of a different php extension, which does have support for LIBXML_PARSEHUGE

Although I have been thinking about option B for years, I never came around to implementing it, as it is not a trivial task, and besides converting the xml parser we would need to set up benchmarking code to make sure that the performance profile did not get significantly worse...

Having said all that, I think that stream-based reading is a great addition, that could make the library perform much better when dealing with big messages (ie. consume less memory).

So yes, please go on and submit a PR :-), and we will move the discussion forward starting from there!

**Comment by gabrielspiteri-highlight** [comment]
@gggeek thanks for your feedback. I have added a PR with my code change to handle the issue. Thanks

**Comment by gggeek** [comment]
Implemented in 4.4.0
