### ISSUE TITLE
Switch to PSR Logger and allow DI patterns

### ISSUE THREAD

**Issue by kor3k** [gggeek/phpxmlrpc#78]
The logger [used here](https://github.com/gggeek/phpxmlrpc/blob/master/src/Helper/Logger.php) is impossible to replace/override, because of the way it's implemented 

```
Logger::instance()->debugMessage($message)
```

also it's debug = 2 mode just echoes/prints debug message to the output, which has not much use when phpxmlrpc is used for example in the queue consumer.

replacing it with [PSR Logger](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md) would be much more flexible and allow users to use mainstream php loggers like [Monolog](https://github.com/Seldaek/monolog). 
this would also eliminate the `PhpXmlRpc\Client::$debug` variable by using proper PSR Logger loglevel methods.

**Comment by gggeek** [comment]
You are right that atm it is not always easy or even possible to swap out bits of the library, such as the logger, with alternative implementations.
The reason is simple: the library design predates by a wide margin the spread of DI patterns in the php ecosystem, or for that matter, PSR/Log.

In the latest releases however, some work has already been done in order to introduce DI patterns, that would allow this.
Specifically, the 'top-level' classes all implement `setLogger` and `getLogger` methods.

Which means that you can already either subclass `PhpXmlRpc\Client` and take over `getLogger`, or keep the existing Client class and add in your code a `setLogger()` call to inject a new logger to your client instances. Of course it is up to you to create a wrapper that implements the phpxmlrpc "logger api" on top of a psr logger.

I noticed that classes Charset, Http and XMLParser do not yet follow this DI pattern, so there is room for improvement there.

On the other hand, the question also stands: when injecting a logger into, say, the client, should the client propagate it its Requests? And should the Requests propagate it to their XMLParser?

Last words of feedback: this library prizes stability and backwards compatibility over anything else. So, while I am willing to make it easy or at least possible to use psr\log and DI patterns, this will not be done at the cost of BC, at least not until there is a new major version in the pipe.

WDYT?

**Comment by gggeek** [comment]
ps. DOH!
I just realized that the code which makes it possible to swap out the logger is only in the master branch.
Would you be willing to test if it fits your requirements?
The current plan is to release it for version 4.6.0 - but I also would like to push in a few more new features in that version, and since these are busy times for me, it might not be tagged and released for a couple of months...

**Comment by gggeek** [comment]
ping

**Comment by kor3k** [comment]
oh sorry, i wanted to reply but i forgot.

yes i am looking through it. i can make it PSR-3 compliant, but unfortunately, it won't be without breaking BC.  for example the `setLogger`, `getLogger`, `$logger` are static. this should be replaced with proper DI. so releasing in another version with BC announcement is the way.

> when injecting a logger into, say, the client, should the client propagate it its Requests? And should the Requests propagate it to their XMLParser?

absolutely yes. when instantiating/servicing the client, you inject logger once and expect everything gets logged into that one instance.

i will dig into it during upcoming days.

**Comment by gggeek** [comment]
> ... i can make it PSR-3 compliant, but unfortunately, it won't be without breaking BC. for example the `setLogger`, `getLogger`, `$logger` are static. this should be replaced with proper DI

Care to explain how you are instantiating your Client objects? Are you making it a Service (singleton) via your framework's config, or are you creating a new instance manually?

**Comment by kor3k** [comment]
i am making the client a service (multiple instances actually). but in both service & manual instance, i assume that `Client` and `Server` are the "entry points" which should get injected the logger and propagate it into other classes like `Value`, `Request`, `Response`.

looking at it, some classes which are used as "static property singletons" like the logger should also be serviced and injected, in particular `Encoder` and perhaps everything in `Helper\`.

there are also files in `lib/` which make static calls mostly to `Server`, but they are all marked as "deprecated". so perhaps get rid of them toghether with most (ideally, all) static accesses.

**Comment by gggeek** [comment]
Quoting my initial response:

> Last words of feedback: this library prizes stability and backwards compatibility over anything else. So, while I am willing to make it easy or at least possible to use psr\log and DI patterns, this will not be done at the cost of BC, at least not until there is a new major version in the pipe.

I'll take a look at what can be done for your scenario, but don't hold your breath for breaking changes and removal of old code...

**Comment by kor3k** [comment]
i got your point there, but maybe it's time for new major version then. i know this library started long time ago, but using it with today's frameworks by their means is quite cumbersome. it's a useful lib and imho deserves some refactoring, and to maintain BC keep it in two branches, legacy plus current one.

**Comment by gggeek** [comment]
You are certainly not wrong with that suggestion.
However there a few other things worth pointing out:

- I am maintaining an increasingly large number of open source projects. The time I can afford to dedicate to them is not infinite. Maintaining one extra branch with a mostly different codebase is not a trivial endeavour;
- the "modernize the lib" approach is quite a slippery slope, as there is a ton of things that I would change if shackled from the chains of BC. I even started doing that a little while ago! Just look at all the "phpxmlrpc-ng" repos in my github... Sadly, that project fell by the wayside due to other stuff taking precedence
- I am not sure how popular xmlrpc is nowadays in real life. My gut feeling is that this lib is used mostly by existing projects that adopted it a long time ago. How many users would pick up a new version with a vastly different API?

**Comment by gggeek** [comment]
Btw, version 4.6.0 has been released, with the changes which were implemented in Feb.
So definitely still relying on a lot of static methods, but it should now be possible to at least introduce usage of a PSR-3 Logger with the help of some glue code...

**Comment by gggeek** [comment]
...aaand we are now approaching the situation where it is feasible, and almost, but not quite, nice, to use a Psr/Log compliant logger.

In the next version (planned to be 4.10.0):
- all classes which use the logger can finally have a logger instance injected into them (NB: this is still done via static methods, for BC)
- the logger methods which get called by the library have changed - now they implement the same spec as Psr\Log\Loggerinterface
- a demo file has been added, to showcase how the DI can be achieved. See https://github.com/gggeek/phpxmlrpc/blob/master/demo/client/loggerinjection.php

**Comment by gggeek** [comment]
PS: I was thinking about adding add a method `PhpXmlRpc\PhpXmlRpc::setLogger()` that would alleviate the need for end users to know all of the classes which need the logger to be injected into...

**Comment by Hanmac** [comment]
@gggeek i saw this issue while looking for other PSR stuff

Would it be okay if i would try to make MR for using LoggerInterface?

What about other PSR, might the HTTP-Client one be useful for this? Or is it way too deep with curl connected?

**Comment by Hanmac** [comment]
you got some interesting points

as for a -ng project, i recently experimented with symfony serializer stuff,
and i wonder if that can be used to make the request/response parsing more flexible 

i might use your stuff as inspiration for the different value types i need to respect

**Comment by kor3k** [comment]
> What about other PSR, might the HTTP-Client one
> with symfony serializer stuff

well, that's exactly what i ended up with. 

https://github.com/kor3k/xml-rpc-client

```php

$client = new LoggingClient(
    httpClient: $client,
    requestFactory: $requestFactory,
    streamFactory: $streamFactory,
    rpcRequestParser: new RequestParser($serializer),
    rpcResponseParser: new ResponseParser($serializer),
    onRequest: static fn ($request) => $request
    ->withUri($request->getUri()->withScheme('http')->withHost('betty.userland.com')->withPath('/RPC2'))
);
$client->setLogger($logger);

$response = $client->sendRpcRequest($client->createRpcRequest(method: 'examples.echoParams', params: ['hello', 'world']));
dump([...$response]);        
```

---

it's far less sophisticated than this lib though. just basics.

**Comment by Hanmac** [comment]
> > What about other PSR, might the HTTP-Client one
> > with symfony serializer stuff
> 
> well, that's exactly what i ended up with.
> 
> https://github.com/kor3k/xml-rpc-client
> 

very interesting start, can i add some suggestions?

why not "fully" embrace the power of symfony serializer?

For example, if you put the logic of Serializing inside DataValue using the Normalizeable Interface:
https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Serializer/Normalizer/NormalizableInterface.php

you could handle the whole PHP <=> XML-RPC in one place

**Comment by kor3k** [comment]
> For example, if you put the logic of Serializing inside DataValue using the Normalizeable Interface

there are some issues with this. first is separation of concerns. `DataValueInterface` is just a value holder, nothing more. it should not contain any logic. (yes this is more like an opinion, but it pays out).

second is, that the `PhpNormalizer` takes not only `DataValue`s, but  any data, and [guesses](https://github.com/kor3k/xml-rpc-client/blob/main/src/Parser/Data/PhpNormalizer.php#L56) the correct `DataType`. this would not be possible with `DataValue implements NormalizableInterface`, so you'd need standalone normalizer anyway.

and third, i require it to handle `iterable $data` as i am feeding it with `\Generator` in some cases, which again would not be possible without standalone normalizer.

**Comment by gggeek** [comment]
> and even this could be loosened by introducing some contract like `XmlSerializerInterface`, with `symfony/serializer` as one implementation.

Maybe a bit overkill, but why not...

... I'll have to dig a bit into the "ng" repos to figure out how far away from completeness they are

**Comment by Hanmac** [comment]
>> For example, if you put the logic of Serializing inside DataValue using the Normalizeable Interface
>
> second is, that the `PhpNormalizer` takes not only `DataValue`s, but any data, and [guesses](https://github.com/kor3k/xml-rpc-client/blob/main/src/Parser/Data/PhpNormalizer.php#L56) the correct `DataType`. this would not be possible with `DataValue implements NormalizableInterface`, so you'd need standalone normalizer anyway.

Right now, let the type guessing be done by the normalize functions
I need a way to pass an optional type anyway for base64 stuff

but i added some mapping functions to return the DataValue back into PHP arrays

for example, this unit test in parsing XML:
```php
 $str = '<value><array><data>
<value><string>UstId_1</string></value>
<value><string>DE123456789</string></value>
</data></array></value>';

/**
 * @var $val DataValue
 */
$val = $this->deserialize($str, DataValue::class);
var_dump($val->toPHP());
```

does return this:
```
array(2) {
  [0] =>
  string(7) "UstId_1"
  [1] =>
  string(11) "DE123456789"
}
```

**Comment by kor3k** [comment]
> I need a way to pass an optional type anyway for base64 stuff

base64 is [handled](https://github.com/kor3k/xml-rpc-client/blob/main/src/Parser/Data/PhpNormalizer.php#L60) [here](https://github.com/kor3k/xml-rpc-client/blob/main/src/Parser/Data/PhpNormalizer.php#L85)

```php
$value instanceof StreamInterface => new DataValue(\stream_get_contents($value->detach()), DataType::BASE64),
$value instanceof \SplFileInfo => new DataValue(\file_get_contents($value->getPathname()), DataType::BASE64),
\class_exists(File::class) && $value instanceof File => new DataValue($value->getContent(), DataType::BASE64),
...
DataType::BASE64 => new DataValue(\base64_encode((string) $data->getValue()), $data->getType()),
```

ie. all of these values are base64 encoded during normalization:

```php
SplFileInfo
Psr\Http\Message\StreamInterface
Symfony\Component\HttpFoundation\File\File
new DataValue (string | \Stringable $data, DataType::BASE64)
```

---

if you need custom type with some internal logic, just implement `DataValueInterface` in some class. those de/normalizers are typed against `DataValueInterface`, not `DataValue`.

**Comment by Hanmac** [comment]
@kor3k i mean for my own code, i tried to write my own DataValue object to use with CustomNormalizer (code above)
this part doesn't have DataType as extra parameter yet, but relies on the type of the mixed value
