### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by klarlichter** [gggeek/phpxmlrpc#93]
Hello, if I run your great library I get 

`PhpXmlRpc\Encoder-&gt;decode('&lt;?xml version=&quot;...')`

Could you tell my how to fix this?

**Comment by gggeek** [comment]
Hello.
I am sorry, but I will need more information in order to be able to support you.

What you pasted seems to be a snippet of code, not even an error message. Where do you get it displayed?

The interesting part it seems to be dumped dumped via a layer which does html-escaping, as the ">" character is replaced by "&gt;"
If this is part of an error message, it might be that you copy-pasted some code from the internet, and that when you saved it, but the html-escaping screwed it up...

Would you be able to paste here a full sample of your php code ?

**Comment by gggeek** [comment]
Ping

**Comment by gggeek** [comment]
No feedback for one year. Closing...
