### ISSUE TITLE
Provide support for HTTP/2

### ISSUE THREAD

**Issue by Harrald** [gggeek/phpxmlrpc#94]
`src/Helper/Http.php:124` has the following regex: `/^HTTP\/[0-9]\.[0-9] ([0-9]{3}) /`. This assumes the HTTP protocol always has a version with 2 number and a dot. Thus the regex fails for `HTTP/2` and works for `HTTP/1.1`.

**Comment by gggeek** [comment]
Interesting. 
From a cursory googling around, it seems that there would be more to do that that in order to be able to parse HTTP2 responses, as the whole status line is moved elsewhere, headers names are prefixed with double colons, and cookies are different.
Unless both curl does all the magic and what php gets back from it is basically the same as before (but then, what about the non-curl codepath?).

Do you have an http/2 server publicly available for testing?

**Comment by webIMT** [comment]
I have the same problem here, here is my client with debug level 3 :
---GOT---
HTTP/2 200 
date: Wed, 19 Jan 2022 14:12:51 GMT
server: Apache
content-encoding: gzip
vary: Accept-Encoding
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: sameorigin
x-content-type-options: nosniff
content-security-policy: frame-ancestors 'self'
content-length: 11560
content-type: text/xml;charset=UTF-8

And the error is :
An error occurred: Code: 5 Reason: 'Didn't receive 200 OK from remote server (HTTP/2 200 )'

Sorry, I don't have public server for your test...

**Comment by gggeek** [comment]
A PR was merge which should fix this. I'd like to add some tests before releasing the next version though.

**Comment by scqrzdt** [comment]
/^HTTP\/[0-9](\.[0-9])? ([0-9]{3}) /

**Comment by scqrzdt** [comment]
`/^HTTP\/[0-9](\.[0-9])? ([0-9]{3}) /`

**Comment by gggeek** [comment]
Implemented in rel. 4.7.0

**Comment by webIMT** [comment]
Thank you !

Olivier.
